site_name: PROCASTcable



theme:
  name: material
  features:
    - navigation.instant # ускорение загрузки (SPA)
    - navigation.tracking # динамический URL страницы 
    - navigation.tabs # перенос названий документов в горизонтальное меню
    - navigation.tabs.sticky # горизонтальное меню не скрывается при прокрутке
    - navigation.indexes # главные страницы разделов не отображаются в меню
    - navigation.top # вкл. кнопку возврата наверх

nav:
  - Руководство по установке:
    - ig/index.md
    - Создание репозитория:
      - ig/repo_creation_gh.md
      - ig/repo_creation_gl.md
    - ig/mkdocs_installation.md
  - About: about.md
  - Руководство администратора:
    - ag/index.md
    - ag/setup.md
    - ag/pub_setup.md
  - Bass: 'index.md'
  - 'Абоба': 
    - 'Абобус': 'about.md' 


#theme: readthedocs

theme: 
  name: readthedocs
  extra_css:
  - style.css
  nav_style: dark
  logo: C:\Users\Egor-\Desktop\habr\docopsgh\docs\img\CVG_logo_2021_white.png
  locale: en
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s


#theme:
#  name: mkdocs
#  highlightjs: true
#  hljs_languages:
#    - yaml
#    - rust

plugins:
  - search:
      lang: 
        - en
        - ru
  - print-site:
    add_to_navigation: true # Пункт "Распечатать PDF" в меню, см. след. парам. 
    print_page_title: 'Распечатать PDF' # Название пункта, см. пред. парам.
    add_print_site_banner: false # Выключает ненужный:) баннер на странице печати
    add_table_of_contents: true # Включает отображение содержания
    toc_title: 'Содержание' # Название раздела с содержанием
    toc_depth: 6 # Количество уровней заголовков в содержании
    add_full_urls: false # Отображение адресов ссылок, например: ссылка (https://site) 
    enumerate_headings: false # Отключает нумерацию заголовков 
    enumerate_figures: true # Включает нумерацию рисунков
    add_cover_page: true # Включает отображение титульной страницы 
    cover_page_template: "" # Путь к шаблону титульной страницы
    path_to_pdf: "" # Путь к сгенерированному PDF-документу
    include_css: true # Включает переопределение дефолтных CSS с целью кастомизации
    enabled: true # Включает плагин
    exclude: # Исключает страницы из PDF
      - index.md