site_name: CVGaudio Manuals

#extra_javascript:
  #- javascripts/extra.js

extra_css:
  - stylesheets/extra.css

theme:
  favicon: img/favicon.ico
  logo: img/CVG_logo_2021_white.png
  name: material
  custom_dir: overrides

  #prev_next_buttons_location: none
  #navigation_depth: 2
  #collapse_navigation: false
  #titles_only: True
  #sticky_navigation: true 

  features:
    - navigation.instant # ускорение загрузки (SPA)
    - navigation.tracking # динамический URL страницы 
    - navigation.tabs # перенос названий документов в горизонтальное меню
    #- navigation.tabs.sticky # горизонтальное меню не скрывается при прокрутке
    #- navigation.indexes # главные страницы разделов не отображаются в меню
    - navigation.top # вкл. кнопку возврата наверх
    #- navigation.expand # раскрытие всех веток
    - navigation.path

    #- navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy


  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep orange
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode    
      primary: grey
      accent: lime

nav:
  - Downloads:
      - CVGaudio_UnicoreDX.md
  - manuals:
    - Diga Series:
      - Unicore_DX.md
      - Power_Logic.md
    - 8 Ohm:
      - CVGaudio_CX408.md
      - CVGaudio_CL608.md
      - CVGaudio_TXR608.md
    - Источники:
      - CVGaudio_BLUEFOX.md
      - CVGaudio_M-023Bl.md
  #- Руководство по установке:
  #  - ig/index.md
  #  - Создание репозитория:
  #    - ig/repo_creation_gh.md
  #    - ig/repo_creation_gl.md
  #  - ig/mkdocs_installation.md
  #- About: about.md
  #- Руководство администратора:
  #  - ag/index.md
  #  - ag/setup.md
  #  - ag/pub_setup.md
  #- Bass: 'index.md'
  #- 'Абоба': 
  #  - 'Абобус': 'about.md' 


repo_url: https://www.cvg.ru/
repo_name: cvg.ru

plugins:
  - search:
  #- with-pdf:
        #author: WHO
        #copyright: ANY TEXT
        #
        #cover: false
        #back_cover: true
        #cover_title: TITLE TEXT
        #cover_subtitle: SUBTITLE TEXT
        #custom_template_path: TEMPLATES PATH
        #
        #toc_title: TOC TITLE TEXT
        #heading_shift: false
        #toc_level: 3
        #ordered_chapter_level: 2
        #excludes_children:
        #    - 'release-notes/:upgrading'
        #    - 'release-notes/:changelog'
        #
        #exclude_pages:
        #    - 'bugs/'
        #    - 'appendix/contribute/'
        #convert_iframe:
        #    - src: IFRAME SRC
        #      img: POSTER IMAGE URL
        #      text: ALTERNATE TEXT
        #    - src: ...
        #two_columns_level: 3
        #
        #render_js: true
        #headless_chrome_path: headless-chromium
        #
        #output_path: any-place/document.pdf
        #enabled_if_env: ENABLE_PDF_EXPORT
        #
        #debug_html: true
        #show_anchors: true
        #verbose: true

  - print-site:
      add_to_navigation: false
      print_page_title: 'Print Site'
      add_print_site_banner: true
      # Table of contents
      add_table_of_contents: true
      toc_title: 'Table of Contents'
      toc_depth: 3
      # Content-related
      add_full_urls: false
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: true
      cover_page_template: ""
      path_to_pdf: ""
      include_css: true
      enabled: true
      exclude:
    
  #- page-to-pdf:

